# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 172.24.16.2/20
      gateway4: 172.24.16.1
      nameservers:
              addresses: [8.8.8.8]
  version: 2
